version: '3.2'
services:
  backend:
      build: ./backend
      ports:
        - 5000:5000
      volumes:
        - ./src/model:/src/model
      depends_on:
        - training
  frontend:
      build: ./frontend
      ports:
        - 3000:3000
  training:
      build: ./training
      volumes:
        - ./src/model:/src/model
        - ./src/data:/src/data
        - ./src/imgs:/src/imgs
        